2023
MISW/misw-jp pull request #37
Opened 2023-04-01 14:49 UTC by SnakeSneakS

# プルリクエストを行う前に、以下のことを確認してください。

- [x] コードのフォーマットを行いましたか？
- [x] エラーや警告を出さずに、正しくビルドされることを確認しましたか？
- [ ] 様々なブラウザ・OS・解像度でテストを行い、すべて正常に表示されましたか？
  - とりあえずMacOSでChrome, Safari, FIrefoxは確認しました。
- [x] サイズが 25 MiB を超えるファイルが存在しませんか？
- [x] 画像ファイルや動画ファイルには AVIF や AV1 等の軽量なコーデックを利用していますか？
- [x] ライセンス感染するパッケージやライブラリ等を使用していませんか？ (例: GNU GPL・CC BY-SA)
- [ ] サインオフを行いましたか？ (例: Signed-off-by: mischan <miswchan@misw.jp> )
  - このプルリクテンプレ見るまで完全に忘れてた()
- [x] プルリクエストを送信したら、Web の担当者と SysAd の担当者に、コードレビューをリクエストしてください。

# プルリクエストの内容を以下に記載してください。
1. 会費などの更新
  - /about.html で表示される会費を更新しました。
  - /about.html で表示される部員数を`{TODO}人 2023年3月時点`に変更しました。何人かは知らないので修正して欲しいです...
  - 他、年間スケジュールのゲームジャムや活動時間など「本当にあってる..?」と思ったところは`{TODO}`をコメントとしてつけてみたので確認してみて欲しいです。
2. 新歓Webサイトを作成しないという噂を受けて、去年の新歓サイトへのリンクをいつまでも載せてるの良くないなと思い、Join Usを独断と偏見で作成してみました(去年の新歓サイトのパクリ)。

# 特筆すべき内容があれば以下に記載してください。
- これは提案(Web係じゃないけど誰もやってないしという理由)としてやってみただけなので却下も全然アリです。
- 感想: config.yamlで色々設定できるようになってて感動しました。天才👏

2023-04-01 17:20 UTC, tamacake39 commented
コミットしようと思ったら権限なかったのでconfig.yamlの中身全部貼っちゃいますね
`
event:
  url: 'https://event.misw.jp/c101/'
  image: 'images/og.webp'

blog:
  url: 'https://blog.misw.jp/'

works:
  url: 'https://18dafcde6bdc7f4f399fe8197dd30da9.misw.jp/#works-frame'

jquery:
  url: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js'

fee:
  a:
    name: '入会費' # = 新入生の会費 (overview.f.dataの一部に対応)
    data: '1500'

overview:
  a:
    name: '設立'
    data: '1969年4月16日'
  b:
    name: '部員数'
    data: '90人(内インカレ15人)(2023年3月時点)'
  c:
    name: '活動時間'
    data: '木曜日17:00～19:00<br />土曜日14:00～16:00'
  d:
    name: '活動場所'
    data: '木曜日 早稲田大学西早稲田キャンパス52号館302教室<br />土曜日 Discordによるオンライン活動'
  e:
    name: '部室'
    data: '戸山キャンパス学生会館　E927'
  f:
    name: '会費 (半期)'
    data: '新入生 1500円<br/>既存生 3000円'

kanbu:
  a:
    role: '幹事長'
    name: 'たまかけ'
    group: 'プロ研'
    image: 'img/kanbu/0.webp'
  b:
    role: '副幹事長'
    name: 'せいる'
    group: 'MIDI研'
    image: 'img/kanbu/1.webp'
  c:
    role: '会計'
    name: 'Polar'
    group: 'プロ研'
    image: 'img/kanbu/2.webp'
  d:
    role: 'プログラミング研会長'
    name: '文月まぐ'
    group: 'プロ研'
    image: 'img/kanbu/3.webp'
  e:
    role: 'CG研会長'
    name: 'NOAH'
    group: 'CG研'
    image: 'img/kanbu/4.webp'
  f:
    role: 'MIDI研会長'
    name: '9W3R7Y'
    group: 'MIDI研'
    image: 'img/kanbu/5.webp'

footer:
  contact: 'メールアドレス: misw.info☆gmail.com(☆を@に直して送信してください)<br />Twitter(<a href="https://twitter.com/misw_info" target="_blank" rel="noopener noreferrer">@misw_info</a>)のダイレクトメッセージにお送りいただくこともできます。'
  copyright: 'Copyright (c) 2018-2023, MIS.W（早稲田大学経営情報学会）All rights reserved.'
`
join usもいい感じだと思います。

幹部の写真はみんなに送ってくれ～～って働きかけときますね

2023-04-01 17:26 UTC, tamacake39 commented
と思ったら1月にはRemove: Kanbu されてたのか……じゃあ写真はいいですね

2023-04-01 17:31 UTC, CaffeeLake commented
古い情報を残したままだと良くないという話なので、更新するなら戻していいと思う。
今年の最初の話だと、誰も更新する気がなさそうだったので。

2023-04-01 17:42 UTC, CaffeeLake commented
というか、プライバシーポリシーとか会費の更新とか新歓サイト(あるのかしらないけど)の公開とかは4月になる前には終わらせとかないといけないのでは。
なぜ今頃なんだ...という気持ち。

2023-04-01 18:29 UTC, CaffeeLake requested changes
会費について少し思ったのが、Portalとかも含め入会金と半期の会費と新入生の値段と既存の人の値段みたいな色々な書き方があって、2年以降で新規に入る人が1500円なのか3000円なのか分かりにくいのと、入会金+会費を払わないといけないとも捉えれて分かりにくいと思う。

2023-04-02 01:39 UTC, SnakeSneakS commented
(確認・コメントなど助かるありがとう🙏 @tamacake39 @CaffeeLake )
(プライバシーポリシーとか会費更新とかは、目下新歓対面イベントがある明日までに直せたら直したいよね...のお気持ち...(そういう意味では幹部アイコン更新は後で別ブランチ立ててやるのがいいかも?))
(特にプライバシーポリシーは動き出し遅くてごめん...)

会費についてなるほど！
重複支払い回避も兼ねて、みすポータル・公式HP共に
```
新入生1500円 
既存生3000円 #みすポータルには書かない気もする(?)
```
に統一するのがいいと思ったけど、どうだろう？
(もし二年入会からでも1500円かな?と思い一年生ではなく新入生。違ったら許せ)(新入生という言葉よりいい言葉あったら教えてくれると助かる)
ちなみに同様の書き方してるのは[去年の春学期会費徴収](https://misw.kibe.la/@nanasiro/7074)とか
(これはみすポータル関わってたぽいまぐくんにもメンション追加しとこ@3kanAlpha )

2023-04-02 01:55 UTC, SnakeSneakS commented
部員数90人になるのか...そういえば1~4年まで在籍可能になったことでkibelaの100人制限を突破してしまう可能性出てきたな...
kibelaを継続するなら、[Web API](https://github.com/kibela/kibela-api-v1-document) を管理者アカウントで叩いて管理者以外のアカウント削除[分からんけどこれとか?](https://github.com/kibela/kibela-api-v1-document/blob/master/schema.graphql#L2562-L2567)を自動的にやる、とかの思い切りがいるかもしれんね...(或いはkibelaを辞めてしまうか? 記事の移行は大変そうだけど、kibelaにメールしたら全記事エクスポートやってくれるかもしれないですしおすし...)

2023-04-02 01:57 UTC, CaffeeLake commented
Kibelaの記事のエクスポートは管理者なら設定から出来るらしい。

2023-04-02 02:05 UTC, SnakeSneakS commented
> Kibelaの記事のエクスポートは管理者なら設定から出来るらしい。

@CaffeeLake 
なるほど！
（後ごめんここに置いとくと会話が続いた時に公式HPへのプルリクの動きが鈍くなっちゃうそうと思い直しててきとーに[別の場所](https://github.com/MISW/k8s/issues/865) に移したので、そっちでお願い...）

2023-04-02 04:25 UTC, tamacake39 commented
新入会員、既存会員の会費の話
意図するところは2年生でも新入会員は1500円ということです。入会費が1500円って書き方はいけないですね。
会費:新入会員1500円・既存会員3000円みたいな表記がいいかな（あれ、変わってない？）

2023-04-02 04:28 UTC, CaffeeLake approved these changes

2023-04-02 05:00 UTC, SnakeSneakS commented
[新規入会/継続会員](https://github.com/MISW/misw-jp/pull/37/files#diff-d8d0422389f03d783e32e627250fe29834bd09c6361640d1ff00661dd6820034R35-R41)表記もそれはそれでいいか(新入会員/既存会員とどっちがいいかは任せる)

ヘビからはもう何もないです！LGTMということで...

2023-04-02 05:06 UTC, SnakeSneakS commented
portalの方でも会費について学年問わず入会費1500円だっていう[プルリク](https://github.com/MISW/portal/pull/1041)出しておきました ノ

2023-04-02 09:51 UTC, merged